### ISSUE TITLE
Proposal: Beginner: Short Talk: Building a Go library over BudgetSMS API by Souvik Haldar

### ISSUE THREAD

**Issue by algogrit** [golangindia/StudyGroup#12]
### Abstract:
Algorithm to verify sms OTP using Redis and gobudgetsms.
Gobudgetsms: Library around the Budget SMS API by Souvik Haldar, Kolkata

### Links:
1. https://github.com/souvikhaldar/gobudgetsms

----

# Speaker Bio

### Name: Souvik Haldar
Backend Developer at Kartbites

----

### Self Declaration:
Please replace the blank space within the square bracket with an `x` to tick the box.

- [x] I have read and understood the [Go Community Code of Conduct](https://golang.org/conduct)
- [x] I have read and understood the StudyGroup [Rules & Guidelines](https://github.com/golangindia/StudyGroup/blob/master/RULES_AND_GUIDELINES.md)
- [x] I have already consulted and obtained clearance from all stakeholders about any Intellectual Property. I’m solely responsible for the content I present.

**Comment by souvikhaldar** [comment]
For reference- https://medium.com/@souvikhaldar32/otp-verification-over-sms-using-go-redis-and-gobudgetsms-1b631419ca06
