### ISSUE TITLE
Beginner: Any: Learning Standard Package Layout

### ISSUE THREAD

**Issue by souvikhaldar** [golangindia/StudyGroup#16]
### Request:
While trying to figure out the best way to structure a golang project I came across this article https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1
But I couldn't understand it completely. So can anyone take up this topic for upcoming meetup session and explain? Or explain some better way to structure application? 
### References:
https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1

**Comment by pshirali** [comment]
Hi @souvikhaldar ,

Nice topic. Thanks for posting this. Yes, we could take this up for group-discussion. It is possible that each of us might have our own take on the best ways to structure a package though.

Could you mention which parts of the blog you had difficulty understanding? It might provide some pointers to others here to ponder about those aspects too.

Personally, I agree with all the flawed approaches mentioned in the blog. However, I have a different take on items mentioned in the `better approach` section. I think it'd make for a good healthy discussion.

Thanks.

**Comment by souvikhaldar** [comment]
Most confusing part was using mock subpackage. But I request to explain the entire idea, even the purpose of using multiple binary executable was not clear much. If you have a different take on structuring the project, please do explain that. I'm expecting an ideal conclusion of having one way of structuring that I can adopt from now on.

**Comment by rrjanbiah** [comment]
I'm still a noob here. But, looks like above discussion is about pre `dep` era.. isn't it?

**Comment by souvikhaldar** [comment]
It is not much related to dependency management but how you structure your go project.

**Comment by devdinu** [comment]
We've discussed this in last session https://www.youtube.com/watch?v=QZtOt9HwsSs
