### ISSUE TITLE
Intermediate: Talk: Getting familiar with Go Memory Allocation

### ISSUE THREAD

**Issue by ankur-anand** [golangindia/StudyGroup#18]
### Abstract:
Understanding the memory allocator in go.

...

### Prerequisites
1. Basic Go
2. Operating System basic

----

# Speaker Bio

### Name: Ankur Anand
[ankuranand](https://ankuranand.com)

----

### Self Declaration:
Please replace the blank space within the square bracket with an `x` to tick the box.

- [x] I have read and understood the [Go Community Code of Conduct](https://golang.org/conduct)
- [x] I have read and understood the StudyGroup [Rules & Guidelines](https://github.com/golangindia/StudyGroup/blob/master/RULES_AND_GUIDELINES.md)
- [x] I have already consulted and obtained clearance from all stakeholders about any Intellectual Property. I'm solely responsible for the content I present.

### Proposed Dates:
21-Feb-2019

**Comment by pshirali** [comment]
A link to @ankur-anand 's blog post:
https://blog.learngoprogramming.com/a-visual-guide-to-golang-memory-allocator-from-ground-up-e132258453ed
